services:
  - type: web
    name: bardspeak
    env: python
    runtime: python-3.11.9
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: bardspeak-db
          property: connectionString

databases:
  - name: bardspeak-db
    databaseName: shakespeare_club
    user: bardspeak
